### ISSUE TITLE
Issue: Improperly formatted workflow yaml file causes "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by vcolanoKH** [nektos/act#1144]
## System information

- Operating System: macOS
- Architecture: 64bit
- Apple M1: no
- Docker version: 20.10.14
- Docker image used in `act`: nektos/act 
- `act` version: 0.2.26

## Expected behaviour

Yaml parsing syntax error or otherwise error specifying that yaml file cannot be run as a github workflow.

## Actual behaviour

Cryptic go error is given.

## Workflow and/or repository

<details>
  <summary>workflow</summary>

```
name: bug
on:
  pull_request: [synchronize]

jobs:
  bug:
    runs-on: ubuntu-18.04
    steps:
      -
      - name: step
        run: echo "bug"
```

</details>

## Steps to reproduce

`act pull_request -W .github/workflows/bug.yml -v -P nektos/act`

## `act` output

<details>
  <summary>Log</summary>

```
❯ act pull_request -W .github/workflows/bug.yml -v -P nektos/act
DEBU[0000] Loading environment from /Users/vito/dev/redsetter/.env
DEBU[0000] Loading secrets from /Users/vito/dev/redsetter/.secrets
DEBU[0000] Loading workflow '/Users/vito/dev/redsetter/.github/workflows/bug.yml'
DEBU[0000] Reading workflow '/Users/vito/dev/redsetter/.github/workflows/bug.yml'
DEBU[0000] Planning event: pull_request
DEBU[0000] Loading slug from git directory '/Users/vito/dev/redsetter/.git'
DEBU[0000] Found revision: f2a25115b51440edb9a44c6882044454c1b90f5f
DEBU[0000] evaluating expression 'success()'
DEBU[0000] expression 'success()' evaluated to 'true'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x16b6fd8]

goroutine 9 [running]:
github.com/nektos/act/pkg/runner.newJobExecutor({0x1986d78?, 0xc0003bdc20})
        /private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/runner/job_executor.go:35 +0x238
github.com/nektos/act/pkg/runner.(*RunContext).Executor.func1({0x19841f8, 0xc0000a3680})
        /private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/runner/run_context.go:290 +0x55
github.com/nektos/act/pkg/common.Executor.Finally.func1({0x19841f8, 0xc0000a3680})
        /private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/common/executor.go:177 +0x34
github.com/nektos/act/pkg/runner.(*runnerImpl).NewPlanExecutor.func1.1({0x19841f8, 0xc00041e5d0})
        /private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/runner/runner.go:171 +0x2f2
github.com/nektos/act/pkg/common.NewParallelExecutor.func1.1(0x0?, 0x0?)
        /private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/common/executor.go:102 +0x5c
created by github.com/nektos/act/pkg/common.NewParallelExecutor.func1
        /private/tmp/act-20220322-14079-18pjzcc/act-0.2.26/pkg/common/executor.go:100 +0x89
```

</details>

**Comment by ChristopherHX** [comment]
Thank you for reporting this

> Improperly formatted workflow yaml file

the yaml syntax is perfectly fine. Someone decided to decode the steps into an array of pointers, so the yaml parser decoded an null value, to a nil value => crash.

I drafted a Pullrequest to fix the crash.

**Comment by KnisterPeter** [comment]
Besides that the workflow is valid yaml syntax it is semantically not correct.
Currently it's out of scope for act to check semantic, but actionlint can be used to do so: https://rhysd.github.io/actionlint/
