### ISSUE TITLE
SIGSEGV when having secrets not defined locally

### ISSUE THREAD

**Issue by ikamensh** [nektos/act#1306]
### Bug report info

```plain text
act version:            0.2.30
GOOS:                   darwin
GOARCH:                 amd64
NumCPU:                 12
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
        /var/run/docker.sock
Config files:           
        /Users/kai7rng/.actrc:
                -P ubuntu-latest=catthehacker/ubuntu:act-latest
                -P ubuntu-22.04=catthehacker/ubuntu:act-22.04
                -P ubuntu-20.04=catthehacker/ubuntu:act-20.04
                -P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
        Go version:            go1.18.4
        Module path:           command-line-arguments
        Main version:          
        Main path:             
        Main checksum:         
        Build settings:
                -compiler:            gc
                -ldflags:             -X main.version=0.2.30
                CGO_ENABLED:          1
                CGO_CFLAGS:           
                CGO_CPPFLAGS:         
                CGO_CXXFLAGS:         
                CGO_LDFLAGS:          
                GOARCH:               amd64
                GOOS:                 darwin
                GOAMD64:              v1
Docker Engine:
        Engine version:        20.10.17
        Engine runtime:        runc
        Cgroup version:        2
        Cgroup driver:         cgroupfs
        Storage driver:        overlay2
        Registry URI:          https://index.docker.io/v1/
        OS:                    Docker Desktop
        OS type:               linux
        OS version:            
        OS arch:               x86_64
        OS kernel:             5.10.104-linuxkit
        OS CPU:                6
        OS memory:             7859 MB
        Security options:
                name=seccomp,profile=default
                name=cgroupns
```

### Command used with act

```sh
act
```

### Describe issue

Not user friendly way of failing on unknown secrets.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x16291ea]

goroutine 38 [running]:
```

### Workflow content

```yml
Relevant is only that I have following in my .yaml:

${{ secrets.RESOURCE_USER_NAME }}
```

### Relevant log output

```sh
[ci-pipeline/documentation] [DEBUG] evaluating expression 'format('{0}', secrets.RESOURCE_USER_NAME)'
[ci-pipeline/documentation] [DEBUG] expression 'format('{0}', secrets.RESOURCE_USER_NAME)' evaluated to '%!t(string=)'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x16291ea]
```

**Comment by egidijus** [comment]
@ikamensh 

1. are you on an M1 mac? (I see `GOARCH=amd64`)
2. did you recently install monterey v 12.5.1 ?
3. are you running act binary? or in a docker?
4. if binary, did you install from brew or download a release bin from repo?

**Comment by ikamensh** [comment]
1. No, it's intel macbook pro
2. Macos version is 11.6 Big Sur
3. I did `brew install act`, I at least do nothing to run it in a docker.

**Comment by ikamensh** [comment]
Here is example yaml that causes the crash:
```yaml
name: ci-pipeline
on: ["push"]

jobs:
  py38-lin:
    runs-on: [self-hosted, Linux, docker]
    container:
      image: python:3.8-slim
      credentials:
        username: ${{ secrets.RESOURCE_USER_NAME }}
        password: ${{ secrets.BDC_ARTIFACTORY_RESOURCE_TOKEN }}
    steps:
      - name: Configure
        if: ${{ !startsWith(runner.name, 'bla') }}
        run: echo "HELLO"
```

Here is the stack trace:
```
DEBU[0000] Loading environment from /Users/kai7rng/PycharmProjects/try_act/.env 
DEBU[0000] Loading secrets from /Users/kai7rng/PycharmProjects/try_act/.secrets 
DEBU[0000] Loading workflows from '/Users/kai7rng/PycharmProjects/try_act/.github/workflows' 
DEBU[0000] Loading workflows recursively                
DEBU[0000] Found workflow 'ci.yaml' in '/Users/kai7rng/PycharmProjects/try_act/.github/workflows/ci.yaml' 
DEBU[0000] Reading workflow '/Users/kai7rng/PycharmProjects/try_act/.github/workflows/ci.yaml' 
DEBU[0000] Planning event: push                         
DEBU[0000] Loading slug from git directory '/Users/kai7rng/PycharmProjects/try_act/.git' 
DEBU[0000] Loading revision from git directory '/Users/kai7rng/PycharmProjects/try_act/.git' 
DEBU[0000] Found revision: cf976886cf529d70aae21c5238c6c33a4b217f28 
DEBU[0000] HEAD points to 'cf976886cf529d70aae21c5238c6c33a4b217f28' 
DEBU[0000] using github ref: refs/heads/feature/boom    
DEBU[0000] Found revision: cf976886cf529d70aae21c5238c6c33a4b217f28 
[ci-pipeline/py38-lin] [DEBUG] evaluating expression 'success()'
[ci-pipeline/py38-lin] [DEBUG] expression 'success()' evaluated to 'true'
[ci-pipeline/py38-lin] [DEBUG] Loading slug from git directory '/Users/kai7rng/PycharmProjects/try_act/.git'
[ci-pipeline/py38-lin] [DEBUG] Loading revision from git directory '/Users/kai7rng/PycharmProjects/try_act/.git'
[ci-pipeline/py38-lin] [DEBUG] Found revision: cf976886cf529d70aae21c5238c6c33a4b217f28
[ci-pipeline/py38-lin] [DEBUG] HEAD points to 'cf976886cf529d70aae21c5238c6c33a4b217f28'
[ci-pipeline/py38-lin] [DEBUG] using github ref: refs/heads/feature/boom
[ci-pipeline/py38-lin] [DEBUG] Found revision: cf976886cf529d70aae21c5238c6c33a4b217f28
[ci-pipeline/py38-lin] [DEBUG] expression '${{ secrets.RESOURCE_USER_NAME }}' rewritten to 'format('{0}', secrets.RESOURCE_USER_NAME)'
[ci-pipeline/py38-lin] [DEBUG] evaluating expression 'format('{0}', secrets.RESOURCE_USER_NAME)'
[ci-pipeline/py38-lin] [DEBUG] expression 'format('{0}', secrets.RESOURCE_USER_NAME)' evaluated to '%!t(string=)'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x16291ea]

goroutine 32 [running]:
github.com/nektos/act/pkg/runner.useStepLogger.func1({0x18b7a98?, 0xc0004c0a80?})
        /private/tmp/act-20220801-4014-thiodr/act-0.2.30/pkg/runner/job_executor.go:136 +0x26a
github.com/nektos/act/pkg/common.Executor.Finally.func1({0x18b7a98, 0xc0004c0a80})
        /private/tmp/act-20220801-4014-thiodr/act-0.2.30/pkg/common/executor.go:175 +0x34
github.com/nektos/act/pkg/runner.newJobExecutor.func5({0x18b7a98, 0xc0004c0a80})
        /private/tmp/act-20220801-4014-thiodr/act-0.2.30/pkg/runner/job_executor.go:116 +0xb1
github.com/nektos/act/pkg/common.Executor.Finally.func1({0x18b7a98, 0xc0004c0a80})
        /private/tmp/act-20220801-4014-thiodr/act-0.2.30/pkg/common/executor.go:176 +0x52
github.com/nektos/act/pkg/common.Executor.Finally.func1({0x18b7a98, 0xc0004c0a80})
        /private/tmp/act-20220801-4014-thiodr/act-0.2.30/pkg/common/executor.go:175 +0x34
github.com/nektos/act/pkg/common.Executor.Finally.func1({0x18b7a98, 0xc0004c0a80})
        /private/tmp/act-20220801-4014-thiodr/act-0.2.30/pkg/common/executor.go:175 +0x34
github.com/nektos/act/pkg/runner.(*RunContext).Executor.func1({0x18b7a98, 0xc0004c0a80})
        /private/tmp/act-20220801-4014-thiodr/act-0.2.30/pkg/runner/run_context.go:286 +0x7e
github.com/nektos/act/pkg/common.Executor.Finally.func1({0x18b7a98, 0xc0004c0a80})
        /private/tmp/act-20220801-4014-thiodr/act-0.2.30/pkg/common/executor.go:175 +0x34
github.com/nektos/act/pkg/runner.(*runnerImpl).NewPlanExecutor.func1.1({0x18b7a98, 0xc0004888a0})
        /private/tmp/act-20220801-4014-thiodr/act-0.2.30/pkg/runner/runner.go:195 +0x362
github.com/nektos/act/pkg/common.NewParallelExecutor.func1.1(0x0?, 0x0?)
        /private/tmp/act-20220801-4014-thiodr/act-0.2.30/pkg/common/executor.go:100 +0x5c
created by github.com/nektos/act/pkg/common.NewParallelExecutor.func1
        /private/tmp/act-20220801-4014-thiodr/act-0.2.30/pkg/common/executor.go:98 +0x89
```
