### ISSUE TITLE
Artifactcache: Failed to save cache entry 'already exist'

### ISSUE THREAD

**Issue by ChristianHersevoort** [nektos/act#1787]
### Bug report info

```plain text
act version:            0.2.45
GOOS:                   linux
GOARCH:                 amd64
NumCPU:                 16
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
        /var/run/docker.sock
Config files:           
        /home/christian/.actrc:
                -P ubuntu-latest=catthehacker/ubuntu:act-latest
                -P ubuntu-20.04=catthehacker/ubuntu:act-20.04
                -P ubuntu-18.04=catthehacker/ubuntu:act-18.04
                ubuntu-16.04=catthehacker/ubuntu:act-16.04
Build info:
        Go version:            go1.20.3
        Module path:           github.com/nektos/act
        Main version:          (devel)
        Main path:             github.com/nektos/act
        Main checksum:         
        Build settings:
                -buildmode:           pie
                -compiler:            gc
                -trimpath:            true
                CGO_ENABLED:          1
                GOARCH:               amd64
                GOOS:                 linux
                GOAMD64:              v1
                vcs:                  git
                vcs.revision:         25dd7a13c00002e8fad19eca9f03a67d4ff8163a
                vcs.time:             2023-05-02T14:22:58Z
                vcs.modified:         true
Docker Engine:
        Engine version:        23.0.3
        Engine runtime:        runc
        Cgroup version:        2
        Cgroup driver:         systemd
        Storage driver:        overlay2
        Registry URI:          https://index.docker.io/v1/
        OS:                    Arch Linux
        OS type:               linux
        OS version:            
        OS arch:               x86_64
        OS kernel:             6.2.10-arch1-1
        OS CPU:                16
        OS memory:             32044 MB
        Security options:
                name=seccomp,profile=builtin
                name=cgroupns
```

### Command used with act

```sh
act pull_request
```

### Describe issue

Re-running act build fails because the cache entry already exists, however this works fine on github-actions.

1. run pr-builder 
2. it runs successfully and uploads files to the Artifactcache
3. run pr-builder again (without any changes), the  cache is restored as expected
4. get the unexpected error: {"error":"already exist"}'

### Workflow content

```yml
name: PR builder
run-name: Building PR for ${{ github.ref }}
on:
    workflow_dispatch:
    pull_request:
env:
  TZ: "Europe/Amsterdam"
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true
jobs:
  pr-builder:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Build with gradle and test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            build
            --build-cache
            -x test
          cache-read-only: false
          generate-job-summary: true
```

### Relevant log output

```sh
[Master builder/pr-builder]   | [command]/bin/tar --posix -cf cache.tgz --exclude cache.tgz -P -C /home/christian/backend --files-from manifest.txt -z
[Master builder/pr-builder]   💬  ::debug::File Size: 159217427
[Master builder/pr-builder]   💬  ::debug::Reserving Cache
[Master builder/pr-builder]   💬  ::debug::Resource Url: http://192.168.50.187:35649/_apis/artifactcache/caches
[Master builder/pr-builder]   💬  ::debug::Saving Cache (ID: 10)
[Master builder/pr-builder]   💬  ::debug::Upload cache
[Master builder/pr-builder]   💬  ::debug::Resource Url: http://192.168.50.187:35649/_apis/artifactcache/caches/10
[Master builder/pr-builder]   💬  ::debug::Upload concurrency: 4
[Master builder/pr-builder]   💬  ::debug::Upload chunk size: 33554432
[Master builder/pr-builder]   💬  ::debug::Awaiting all uploads
[Master builder/pr-builder]   💬  ::debug::Uploading chunk of size 33554432 bytes at offset 0 with content range: bytes 0-33554431/*
[Master builder/pr-builder]   💬  ::debug::Uploading chunk of size 33554432 bytes at offset 33554432 with content range: bytes 33554432-67108863/*
[Master builder/pr-builder]   💬  ::debug::Uploading chunk of size 33554432 bytes at offset 67108864 with content range: bytes 67108864-100663295/*
[Master builder/pr-builder]   💬  ::debug::Uploading chunk of size 33554432 bytes at offset 100663296 with content range: bytes 100663296-134217727/*
[Master builder/pr-builder]   💬  ::debug::Uploading chunk of size 24999699 bytes at offset 134217728 with content range: bytes 134217728-159217426/*
[Master builder/pr-builder]   💬  ::debug::Commiting cache
[Master builder/pr-builder]   | Cache Size: ~152 MB (159217427 B)
[Master builder/pr-builder]   💬  ::debug::Resource Url: http://192.168.50.187:35649/_apis/artifactcache/caches/10
[Master builder/pr-builder]   | Cache saved successfully
[Master builder/pr-builder]   | Saving cache metadata: {"entries":[{"artifactType":"generated-gradle-jars","pattern":"/root/.gradle/caches/8.0.2/generated-gradle-jars/gradle-api-8.0.2.jar","cacheKey":"generated-gradle-jars-5cf24d491b73da37e3dd6e7322277d24"},{"artifactType":"generated-gradle-jars","pattern":"/root/.gradle/caches/8.0.2/generated-gradle-jars/gradle-kotlin-dsl-extensions-8.0.2.jar","cacheKey":"generated-gradle-jars-7f66e5f59bbc91c48429392b53027bf4"},{"artifactType":"wrapper-zips","pattern":"/root/.gradle/wrapper/dists/gradle-8.0.2-bin/25jlreiuz6u3xu2phlpa2vv4m","cacheKey":"wrapper-zips-cc7b4be6c9118a3453f8df3bdcb64c9b"},{"artifactType":"dependencies","pattern":"/root/.gradle/caches/modules-*/files-*/*/*/*/*","cacheKey":"dependencies-67ee4a086298411f07bad408dff79076"},{"artifactType":"instrumented-jars","pattern":"/root/.gradle/caches/jars-*/*","cacheKey":"instrumented-jars-0b0798f76b0dfc91f4fac6d62df23ab8"},{"artifactType":"kotlin-dsl","pattern":"/root/.gradle/caches/*/kotlin-dsl/*/*","cacheKey":"kotlin-dsl-85e1428aa7e5aa440188d98ebef12976"}]}
[Master builder/pr-builder]   | Gradle User Home (directories >5M): after extracting common artifacts (only 'caches' and 'notifications' will be stored)
[Master builder/pr-builder]   |   19M    ./caches/modules-2/metadata-2.100/descriptors
[Master builder/pr-builder]   |   20M    ./caches/modules-2/metadata-2.100
[Master builder/pr-builder]   |   6.0M    ./caches/modules-2/files-2.1
[Master builder/pr-builder]   |   26M    ./caches/modules-2
[Master builder/pr-builder]   |   22M    ./caches/transforms-3
[Master builder/pr-builder]   |   17M    ./caches/build-cache-1
[Master builder/pr-builder]   |   20M    ./caches/8.0.2/javaCompile
[Master builder/pr-builder]   |   22M    ./caches/8.0.2
[Master builder/pr-builder]   |   86M    ./caches
[Master builder/pr-builder]   |   88M    .
[Master builder/pr-builder]   |   88M    total
[Master builder/pr-builder]   | -----------------------
[Master builder/pr-builder]   | Caching Gradle User Home with cache key: v7-gradle|Linux|pr-builder[99914b932bd37a50b983c5e7c90ae93b]-c8b44859bd74b53b74b47c01a30722c9a055ff3a
[Master builder/pr-builder]   | Using cache paths: /root/.gradle/caches,/root/.gradle/notifications,/root/.gradle/.gradle-build-action
[Master builder/pr-builder]   💬  ::debug::Checking zstd --quiet --version
[Master builder/pr-builder]   💬  ::debug::Unable to locate executable file: zstd. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
[Master builder/pr-builder]   💬  ::debug::
[Master builder/pr-builder]   💬  ::debug::zstd version: null
[Master builder/pr-builder]   💬  ::debug::implicitDescendants 'false'
[Master builder/pr-builder]   💬  ::debug::followSymbolicLinks 'true'
[Master builder/pr-builder]   💬  ::debug::implicitDescendants 'false'
[Master builder/pr-builder]   💬  ::debug::omitBrokenSymbolicLinks 'true'
[Master builder/pr-builder]   💬  ::debug::Search path '/root/.gradle/caches'
[Master builder/pr-builder]   💬  ::debug::Search path '/root/.gradle/notifications'
[Master builder/pr-builder]   💬  ::debug::Search path '/root/.gradle/.gradle-build-action'
[Master builder/pr-builder]   💬  ::debug::Matched: ../../../../../root/.gradle/caches
[Master builder/pr-builder]   💬  ::debug::Matched: ../../../../../root/.gradle/notifications
[Master builder/pr-builder]   💬  ::debug::Matched: ../../../../../root/.gradle/.gradle-build-action
[Master builder/pr-builder]   💬  ::debug::Cache Paths:
[Master builder/pr-builder]   💬  ::debug::["../../../../../root/.gradle/caches","../../../../../root/.gradle/notifications","../../../../../root/.gradle/.gradle-build-action"]
[Master builder/pr-builder]   💬  ::debug::Archive Path: /tmp/20c03a12-6411-45ff-aa00-a3cacda7e0c4/cache.tgz
[Master builder/pr-builder]   | [command]/bin/tar --posix -cf cache.tgz --exclude cache.tgz -P -C /home/christian/backend --files-from manifest.txt -z
[Master builder/pr-builder]   💬  ::debug::File Size: 28646105
[Master builder/pr-builder]   💬  ::debug::Reserving Cache
[Master builder/pr-builder]   💬  ::debug::Resource Url: http://192.168.50.187:35649/_apis/artifactcache/caches
[Master builder/pr-builder]   🚧  ::warning::Failed to save cache entry with path '/root/.gradle/caches,/root/.gradle/notifications,/root/.gradle/.gradle-build-action,gzip,1.0' and key: v7-gradle|Linux|pr-builder[99914b932bd37a50b983c5e7c90ae93b]-c8b44859bd74b53b74b47c01a30722c9a055ff3a: Error: {"error":"already exist"}
[Master builder/pr-builder]   | Error: {"error":"already exist"}
[Master builder/pr-builder]   |     at Object.<anonymous> (/run/act/actions/gradle-gradle-build-action@v2/dist/post/index.js:212:23)
[Master builder/pr-builder]   |     at Generator.next (<anonymous>)
[Master builder/pr-builder]   |     at fulfilled (/run/act/actions/gradle-gradle-build-action@v2/dist/post/index.js:35:58)
[Master builder/pr-builder]   |     at runMicrotasks (<anonymous>)
[Master builder/pr-builder]   |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[Master builder/pr-builder]   ❓  ::endgroup::
[Master builder/pr-builder]   | Writing job summary
[Master builder/pr-builder]   ✅  Success - Post Build with gradle and test
[Master builder/pr-builder] [DEBUG] Found revision: c8b44859bd74b53b74b47c01a30722c9a055ff3a
[Master builder/pr-builder] [DEBUG] Found revision: c8b44859bd74b53b74b47c01a30722c9a055ff3a
[Master builder/pr-builder] [DEBUG] Found revision: c8b44859bd74b53b74b47c01a30722c9a055ff3a
[Master builder/pr-builder] [DEBUG] setupEnv => map[ACT:true ACTIONS_CACHE_URL:http://192.168.50.187:35649/ CI:true GITHUB_ACTION:1 GITHUB_ACTIONS:true GITHUB_ACTION_PATH: GITHUB_ACTION_REF:v3 GITHUB_ACTION_REPOSITORY:actions/setup-java GITHUB_ACTOR:nektos/act GITHUB_API_URL:https://api.github.com GITHUB_BASE_REF: GITHUB_ENV:/var/run/act/workflow/envs.txt GITHUB_EVENT_NAME:pull_request GITHUB_EVENT_PATH:/var/run/act/workflow/event.json GITHUB_GRAPHQL_URL:https://api.github.com/graphql GITHUB_HEAD_REF: GITHUB_JOB:pr-builder GITHUB_OUTPUT:/var/run/act/workflow/outputcmd.txt GITHUB_PATH:/var/run/act/workflow/pathcmd.txt GITHUB_REF:refs/pull/%!f(<nil>)/merge GITHUB_REF_NAME:%!f(<nil>)/merge GITHUB_REF_TYPE: GITHUB_REPOSITORY:<repo> GITHUB_REPOSITORY_OWNER:<owner> GITHUB_RETENTION_DAYS:0 GITHUB_RUN_ID:1 GITHUB_RUN_NUMBER:1 GITHUB_SERVER_URL:https://github.com GITHUB_SHA:<gitsha> GITHUB_STATE:/var/run/act/workflow/statecmd.txt GITHUB_STEP_SUMMARY:/var/run/act/workflow/SUMMARY.md GITHUB_TOKEN: GITHUB_WORKFLOW:Master builder GITHUB_WORKSPACE: /home/christian/backend GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED:true GRADLE_BUILD_ACTION_CACHE_RESTORED:true GRADLE_BUILD_ACTION_SETUP_COMPLETED:true INPUT_ARCHITECTURE: INPUT_CACHE: INPUT_CHECK-LATEST:false INPUT_DISTRIBUTION:corretto INPUT_GPG-PASSPHRASE: INPUT_GPG-PRIVATE-KEY: INPUT_JAVA-PACKAGE:jdk INPUT_JAVA-VERSION:17 INPUT_JDKFILE: INPUT_JOB-STATUS:success INPUT_MVN-TOOLCHAIN-ID: INPUT_MVN-TOOLCHAIN-VENDOR: INPUT_OVERWRITE-SETTINGS:true INPUT_SERVER-ID:github INPUT_SERVER-PASSWORD:GITHUB_TOKEN INPUT_SERVER-USERNAME:GITHUB_ACTOR INPUT_SETTINGS-PATH: INPUT_TOKEN: ImageOS:ubuntu22 JAVA_HOME:/opt/hostedtoolcache/Java_Corretto_jdk/17.0.7.7.1/x64 JAVA_HOME_17_X64:/opt/hostedtoolcache/Java_Corretto_jdk/17.0.7.7.1/x64 RUNNER_PERFLOG:/dev/null RUNNER_TRACKING_ID: TZ:Europe/Amsterdam]
[Master builder/pr-builder] [DEBUG] Found revision: c8b44859bd74b53b74b47c01a30722c9a055ff3a
[Master builder/pr-builder] [DEBUG] Found revision: c8b44859bd74b53b74b47c01a30722c9a055ff3a
[Master builder/pr-builder] [DEBUG] evaluating expression 'always()'
[Master builder/pr-builder] [DEBUG] expression 'always()' evaluated to 'true'
[Master builder/pr-builder] ⭐ Run Post actions/setup-java@v3
[Master builder/pr-builder] [DEBUG] Writing entry to tarball workflow/outputcmd.txt len:0
[Master builder/pr-builder] [DEBUG] Writing entry to tarball workflow/statecmd.txt len:0
[Master builder/pr-builder] [DEBUG] Writing entry to tarball workflow/pathcmd.txt len:0
[Master builder/pr-builder] [DEBUG] Writing entry to tarball workflow/envs.txt len:0
[Master builder/pr-builder] [DEBUG] Writing entry to tarball workflow/SUMMARY.md len:0
[Master builder/pr-builder] [DEBUG] Extracting content to '/var/run/act'
[Master builder/pr-builder] [DEBUG] run post step for 'actions/setup-java@v3'
[Master builder/pr-builder] [DEBUG] executing remote job container: [node /var/run/act/actions/actions-setup-java@v3/dist/cleanup/index.js]
[Master builder/pr-builder]   🐳  docker exec cmd=[node /var/run/act/actions/actions-setup-java@v3/dist/cleanup/index.js] user= workdir=
[Master builder/pr-builder] [DEBUG] Exec command '[node /var/run/act/actions/actions-setup-java@v3/dist/cleanup/index.js]'
[Master builder/pr-builder] [DEBUG] Working directory ' /home/christian/backend'
[Master builder/pr-builder]   ✅  Success - Post actions/setup-java@v3
[Master builder/pr-builder] [DEBUG] skipping post step for 'actions/checkout@v3': no action model available
[Master builder/pr-builder] [DEBUG] Removed container: 52589fce7d19285e187de6139c833e53feb3aba72ebe59199dc22e5233cd84a1
[Master builder/pr-builder] [DEBUG]   🐳  docker volume rm act-Master-builder-pr-builder-9232fdf038ad2680e05259f7f822b90691aa717cb011b2e4904dfc69c69b750b
[Master builder/pr-builder] [DEBUG]   🐳  docker volume rm act-Master-builder-pr-builder-9232fdf038ad2680e05259f7f822b90691aa717cb011b2e4904dfc69c69b750b-env
[Master builder/pr-builder] 🏁  Job succeeded
[Master builder/pr-builder] [DEBUG] Found revision: c8b44859bd74b53b74b47c01a30722c9a055ff3a
```

**Comment by wolfogre** [comment]
Since it works fine on GitHub Actions, I guess GitHub Actions may supports overwriting a cache entry.
I will try to do an experiment to verify, if the guess is true, I will update the logic in act.
