### ISSUE TITLE
Error: EACCES: permission denied, open '/github/workflow/event.json'

### ISSUE THREAD

**Issue by FezVrasta** [nektos/act#189]
I'm trying to run my GitHUb actions (from the `playwright` branch of https://github.com/popperjs/popper-core) but I get the error below:

```
$ act -j functional-chromium
[...]
[Functional Tests/Chromium Functional Tests]   🐳  docker cp src=/Users/federicozivolo/.cache/act/actions-setup-node@v1 dst=/actions/
| internal/fs/utils.js:220
|     throw err;
|     ^
| 
| Error: EACCES: permission denied, open '/github/workflow/event.json'
|     at Object.openSync (fs.js:440:3)
|     at Object.readFileSync (fs.js:342:35)
|     at new Context (/actions/actions-setup-node@v1/dist/index.js:4688:48)
|     at Object.469 (/actions/actions-setup-node@v1/dist/index.js:9547:19)
|     at __webpack_require__ (/actions/actions-setup-node@v1/dist/index.js:22:30)
|     at Object.202 (/actions/actions-setup-node@v1/dist/index.js:4433:29)
|     at __webpack_require__ (/actions/actions-setup-node@v1/dist/index.js:22:30)
|     at Object.934 (/actions/actions-setup-node@v1/dist/index.js:15205:27)
|     at __webpack_require__ (/actions/actions-setup-node@v1/dist/index.js:22:30)
|     at startup (/actions/actions-setup-node@v1/dist/index.js:37:19) {
|   errno: -13,
|   syscall: 'open',
|   code: 'EACCES',
|   path: '/github/workflow/event.json'
| }
````

**Comment by arzurchris** [comment]
Hi @FezVrasta 
It seems I have the same error, how did you fix it, please?

**Comment by FezVrasta** [comment]
I didn’t 🤦‍♂️
