### ISSUE TITLE
OpenGL all of a sudden not found

### ISSUE THREAD

**Issue by matt-sd-watson** [nektos/act#2438]
### Bug report info

```plain text
act version:            0.2.60
GOOS:                   linux
GOARCH:                 amd64
NumCPU:                 20
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
	/var/run/docker.sock
Config files:           
	/home/matt/.actrc:
		-P ubuntu-latest=catthehacker/ubuntu:act-latest
		-P ubuntu-22.04=catthehacker/ubuntu:act-22.04
		-P ubuntu-20.04=catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
	Go version:            go1.20.14
	Module path:           github.com/nektos/act
	Main version:          (devel)
	Main path:             github.com/nektos/act
	Main checksum:         
	Build settings:
		-buildmode:           exe
		-compiler:            gc
		-ldflags:             -s -w -X main.version=0.2.60 -X main.commit=d3c8664d3d6acb855ae5418f6d02930c98bf877e -X main.date=2024-03-01T02:13:23Z -X main.builtBy=goreleaser
		CGO_ENABLED:          0
		GOARCH:               amd64
		GOOS:                 linux
		GOAMD64:              v1
		vcs:                  git
		vcs.revision:         d3c8664d3d6acb855ae5418f6d02930c98bf877e
		vcs.time:             2024-03-01T02:12:58Z
		vcs.modified:         false
Docker Engine:
	Engine version:        27.1.2
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         systemd
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Ubuntu 22.04.4 LTS
	OS type:               linux
	OS version:            22.04
	OS arch:               x86_64
	OS kernel:             6.8.0-76060800daily20240311-generic
	OS CPU:                20
	OS memory:             64148 MB
	Security options:
		name=apparmor
		name=seccomp,profile=builtin
		name=cgroupns
```

### Command used with act

```sh
act -P ubuntu-22.04=catthehacker/ubuntu:act-22.04
```

### Describe issue

All of a sudden, my local github actions runs receive an error that the OpenGL library could not be opened:
```WARNING: Could not load OpenGL library```

### Workflow content

```yml
name: my_app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: my_app test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        # shell: bash -l {0}
      - name: Install my_app dependencies from requirements
        run: pip install -r requirements.txt
      - name: Install my_app through pip after dependencies
        run: pip install -e .
      - name: Check installed my_app version
        run: my_app -v
      - name: Run pytest for my_app
        shell: bash -l {0}
        run: pytest --headless --cov=my_app
```

### Relevant log output

```sh
WARNING: Could not load OpenGL library.
| Traceback (most recent call last):
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/bin/pytest", line 8, in <module>
|     sys.exit(console_main())
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/_pytest/config/__init__.py", line 189, in console_main
|     code = main()
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/_pytest/config/__init__.py", line 147, in main
|     config = _prepareconfig(args, plugins)
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/_pytest/config/__init__.py", line 328, in _prepareconfig
|     config = pluginmanager.hook.pytest_cmdline_parse(
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
|     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
|     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pluggy/_callers.py", line 55, in _multicall
|     gen.send(outcome)
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/_pytest/helpconfig.py", line 103, in pytest_cmdline_parse
|     config: Config = outcome.get_result()
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
|     raise ex[1].with_traceback(ex[2])
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
|     res = hook_impl.function(*args)
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1067, in pytest_cmdline_parse
|     self.parse(args)
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1354, in parse
|     self._preparse(args, addopts=addopts)
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1237, in _preparse
|     self.pluginmanager.load_setuptools_entrypoints("pytest11")
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
|     plugin = ep.load()
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/importlib/metadata.py", line 86, in load
|     module = import_module(match.group('module'))
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/importlib/__init__.py", line 127, in import_module
|     return _bootstrap._gcd_import(name[level:], package, level)
|   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
|   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
|   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
|   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
|   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
|   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
|   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
|   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/_pytest/assertion/rewrite.py", line 172, in exec_module
|     exec(co, module.__dict__)
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/napari/utils/__init__.py", line 2, in <module>
|     from napari.utils.colormaps.colormap import (
|   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
|   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
|   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/_pytest/assertion/rewrite.py", line 172, in exec_module
|     exec(co, module.__dict__)
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/napari/utils/colormaps/__init__.py", line 2, in <module>
|     from napari.utils.colormaps.colormap import (
|   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
|   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
|   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/_pytest/assertion/rewrite.py", line 172, in exec_module
|     exec(co, module.__dict__)
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/napari/utils/colormaps/colormap.py", line 20, in <module>
|     from napari.utils.color import ColorArray
|   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
|   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
|   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/_pytest/assertion/rewrite.py", line 172, in exec_module
|     exec(co, module.__dict__)
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/napari/utils/color.py", line 7, in <module>
|     from napari.utils.colormaps.standardize_color import transform_color
|   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
|   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
|   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/_pytest/assertion/rewrite.py", line 172, in exec_module
|     exec(co, module.__dict__)
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/napari/utils/colormaps/standardize_color.py", line 27, in <module>
|     from vispy.color import ColorArray, get_color_dict, get_color_names
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/vispy/color/__init__.py", line 12, in <module>
|     from .colormap import (Colormap, BaseColormap,  # noqa
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/vispy/color/colormap.py", line 14, in <module>
|     import vispy.gloo
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/vispy/gloo/__init__.py", line 47, in <module>
|     from . import gl  # noqa
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/vispy/gloo/gl/__init__.py", line 230, in <module>
|     from . import es2 as default_backend  # noqa
|   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/vispy/gloo/gl/es2.py", line 48, in <module>
|     raise OSError('GL ES 2.0 library not found')
| OSError: GL ES 2.0 library not found
```

### Additional information

My application is a Flask and dash app that uses functions from [steinbock](https://github.com/BodenmillerGroup/steinbock), which itself has [napari](https://github.com/napari/napari) as a dependency. It seems that napari is causing the OpenGL error.

When I run these workflows using actual Github Actions, they complete with no errors.

**Comment by matt-sd-watson** [comment]
resolved using:

```
 if: runner.os == 'Linux'
        run: sudo apt-get -y update && sudo apt-get install -y libgl1-mesa-dev
```
