### ISSUE TITLE
cache service url not found

### ISSUE THREAD

**Issue by xenoterracide** [nektos/act#346]
reproducible with
```yml
      - uses: satackey/action-docker-layer-caching@v0.0.8
```
```
[Database Migrations/migrations]   💬  ::debug::getCacheEntry - Attempt 1 of 2 failed with error: Cache Service Url not found, unable to restore cache.
[Database Migrations/migrations]   💬  ::debug::getCacheEntry - Attempt 2 of 2 failed with error: Cache Service Url not found, unable to restore cache.
| Error: getCacheEntry failed: Cache Service Url not found, unable to restore cache.
|     at /actions/satackey-action-docker-layer-caching@v0.0.8/dist/ttsc-dist/main.js/index.js:45734:15
|     at Generator.throw (<anonymous>)
|     at rejected (/actions/satackey-action-docker-layer-caching@v0.0.8/dist/ttsc-dist/main.js/index.js:45665:65)
```

**Comment by tdtm** [comment]
Probably related to https://github.com/nektos/act/issues/329

**Comment by langston-barrett** [comment]
Duplicate of https://github.com/nektos/act/issues/285
