### ISSUE TITLE
When run act locally "❌  Failure - actions/setup-node@v1"

### ISSUE THREAD

**Issue by vinicioslc** [nektos/act#520]
Hi im using Windows 10 with:
nvm: 12.18.3
docker engine: 20.10.2
When i run the example yml i get the following output

The example used to test.
```yml
name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm test
```
Console output (in cmder but prints the same in powershell)
![image](https://user-images.githubusercontent.com/10997022/107121230-08e84e00-6870-11eb-8101-70301252b96e.png)

When I run `act -v`
<details>
<summary>See output</summary>

```shell

λ act -v
time="2021-02-06T11:46:58-03:00" level=debug msg="Loading environment from C:\\Users\\vinicioslc\\Documents\\GitHub\\ks-labs\\table-reports-parser\\.env"
time="2021-02-06T11:46:58-03:00" level=debug msg="Loading secrets from "
time="2021-02-06T11:46:58-03:00" level=debug msg="Loading workflows from 'C:\\Users\\vinicioslc\\Documents\\GitHub\\ks-labs\\table-reports-parser\\.github\\workflows'" time="2021-02-06T11:46:58-03:00" level=debug msg="Reading workflow 'C:\\Users\\vinicioslc\\Documents\\GitHub\\ks-labs\\table-reports-parser\\.github\\workflows\\node.js.yml'"
time="2021-02-06T11:46:58-03:00" level=debug msg="Planning event: push"
time="2021-02-06T11:46:58-03:00" level=debug msg="Loading slug from git directory 'C:\\Users\\vinicioslc\\Documents\\GitHub\\ks-labs\\table-reports-parser\\.git'"
time="2021-02-06T11:46:58-03:00" level=debug msg="Found revision: 0c428ff7d03f6b458fd8584b4b2b9c67f485288b\n"
time="2021-02-06T11:46:58-03:00" level=debug msg="Loading revision from git directory 'C:\\Users\\vinicioslc\\Documents\\GitHub\\ks-labs\\table-reports-parser\\.git'"
time="2021-02-06T11:46:58-03:00" level=debug msg="Found revision: 0c428ff7d03f6b458fd8584b4b2b9c67f485288b\n"
time="2021-02-06T11:46:58-03:00" level=debug msg="HEAD points to '0c428ff7d03f6b458fd8584b4b2b9c67f485288b'"
time="2021-02-06T11:46:58-03:00" level=debug msg="HEAD matches \\refs\\heads\\main"
time="2021-02-06T11:46:58-03:00" level=debug msg="using github ref: \\refs\\heads\\main"
time="2021-02-06T11:46:58-03:00" level=debug msg="context env => map[]"
[CI/test] �  Start image=node:12.6-buster-slim
time="2021-02-06T11:46:58-03:00" level=debug msg="Loading slug from git directory 'C:\\Users\\vinicioslc\\Documents\\GitHub\\ks-labs\\table-reports-parser\\.git'"
time="2021-02-06T11:46:58-03:00" level=debug msg="Found revision: 0c428ff7d03f6b458fd8584b4b2b9c67f485288b\n"
time="2021-02-06T11:46:58-03:00" level=debug msg="Loading revision from git directory 'C:\\Users\\vinicioslc\\Documents\\GitHub\\ks-labs\\table-reports-parser\\.git'"
time="2021-02-06T11:46:58-03:00" level=debug msg="Found revision: 0c428ff7d03f6b458fd8584b4b2b9c67f485288b\n"
time="2021-02-06T11:46:58-03:00" level=debug msg="HEAD points to '0c428ff7d03f6b458fd8584b4b2b9c67f485288b'"
time="2021-02-06T11:46:58-03:00" level=debug msg="HEAD matches \\refs\\heads\\main"
time="2021-02-06T11:46:58-03:00" level=debug msg="using github ref: \\refs\\heads\\main"
[CI/test]   �  docker pull node:12.6-buster-slim
time="2021-02-06T11:46:58-03:00" level=debug msg="Image exists? true"
[CI/test] Removed container: da712143eb2a047740d5b39a2cadba5ebfbd4edeea186dc481460b8a0c221555
[CI/test]   �  docker create image=node:12.6-buster-slim entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[CI/test] Created container name=act-CI-test id=015e7c84303aaa5b5e0461d14d060f05a6a853596f7483c5a050b3a2dc4d44da from image node:12.6-buster-slim
[CI/test] ENV ==> [RUNNER_TOOL_CACHE=/opt/hostedtoolcache RUNNER_OS=Linux RUNNER_TEMP=/tmp]
[CI/test]   �  docker run image=node:12.6-buster-slim entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[CI/test] Starting container: 015e7c84303aaa5b5e0461d14d060f05a6a853596f7483c5a050b3a2dc4d44da
[CI/test] Started container: 015e7c84303aaa5b5e0461d14d060f05a6a853596f7483c5a050b3a2dc4d44da
[CI/test]   �  docker cp src=C:\Users\vinicioslc\Documents\GitHub\ks-labs\table-reports-parser/. dst=\github\workspace
[CI/test] Exec command '[mkdir -p \github\workspace]'
time="2021-02-06T11:47:04-03:00" level=debug msg="Writing tarball C:\\Users\\VINICI~1\\AppData\\Local\\Temp\\act355255767 from C:\\Users\\vinicioslc\\Documents\\GitHub\\ks-labs\\table-reports-parser/."
time="2021-02-06T11:47:04-03:00" level=debug msg="Stripping prefix:C:\\Users\\vinicioslc\\Documents\\GitHub\\ks-labs\\table-reports-parser\\ src:C:\\Users\\vinicioslc\\Documents\\GitHub\\ks-labs\\table-reports-parser/."
[CI/test] Extracting content from 'C:\Users\VINICI~1\AppData\Local\Temp\act355255767' to '\github\workspace'
time="2021-02-06T11:47:07-03:00" level=debug msg="Writing entry to tarball workflow/event.json len:2"
time="2021-02-06T11:47:07-03:00" level=debug msg="Writing entry to tarball home/.act len:0"
[CI/test] Extracting content to '/github/'
time="2021-02-06T11:47:07-03:00" level=debug msg="Loading slug from git directory 'C:\\Users\\vinicioslc\\Documents\\GitHub\\ks-labs\\table-reports-parser\\.git'"
time="2021-02-06T11:47:07-03:00" level=debug msg="Found revision: 0c428ff7d03f6b458fd8584b4b2b9c67f485288b\n"
time="2021-02-06T11:47:07-03:00" level=debug msg="Loading revision from git directory 'C:\\Users\\vinicioslc\\Documents\\GitHub\\ks-labs\\table-reports-parser\\.git'"
time="2021-02-06T11:47:07-03:00" level=debug msg="Found revision: 0c428ff7d03f6b458fd8584b4b2b9c67f485288b\n"
time="2021-02-06T11:47:07-03:00" level=debug msg="HEAD points to '0c428ff7d03f6b458fd8584b4b2b9c67f485288b'"
time="2021-02-06T11:47:07-03:00" level=debug msg="HEAD matches \\refs\\heads\\main"
time="2021-02-06T11:47:07-03:00" level=debug msg="using github ref: \\refs\\heads\\main"
time="2021-02-06T11:47:07-03:00" level=debug msg="setupEnv => map[GITHUB_ACTION:0 GITHUB_ACTIONS:true GITHUB_ACTOR:nektos/act GITHUB_EVENT_NAME:push GITHUB_EVENT_PATH:/github/workflow/event.json GITHUB_REF:\\refs\\heads\\main GITHUB_REPOSITORY:ks-labs/table-reports-parser GITHUB_RUN_ID:1 GITHUB_RUN_NUMBER:1 GITHUB_SHA:0c428ff7d03f6b458fd8584b4b2b9c67f485288b GITHUB_TOKEN: GITHUB_WORKFLOW:CI GITHUB_WORKSPACE:/github/workspace HOME:/github/home]"
time="2021-02-06T11:47:07-03:00" level=debug msg="Loading slug from git directory 'C:\\Users\\vinicioslc\\Documents\\GitHub\\ks-labs\\table-reports-parser\\.git'"
time="2021-02-06T11:47:07-03:00" level=debug msg="Found revision: 0c428ff7d03f6b458fd8584b4b2b9c67f485288b\n"
time="2021-02-06T11:47:07-03:00" level=debug msg="Loading revision from git directory 'C:\\Users\\vinicioslc\\Documents\\GitHub\\ks-labs\\table-reports-parser\\.git'"
time="2021-02-06T11:47:07-03:00" level=debug msg="Found revision: 0c428ff7d03f6b458fd8584b4b2b9c67f485288b\n"
time="2021-02-06T11:47:07-03:00" level=debug msg="HEAD points to '0c428ff7d03f6b458fd8584b4b2b9c67f485288b'"
time="2021-02-06T11:47:07-03:00" level=debug msg="HEAD matches \\refs\\heads\\main"
time="2021-02-06T11:47:07-03:00" level=debug msg="using github ref: \\refs\\heads\\main"
time="2021-02-06T11:47:07-03:00" level=debug msg="context env => map[]"
time="2021-02-06T11:47:07-03:00" level=debug msg="context env => map[GITHUB_ACTION:0 GITHUB_ACTIONS:true GITHUB_ACTOR:nektos/act GITHUB_EVENT_NAME:push GITHUB_EVENT_PATH:/github/workflow/event.json GITHUB_REF:\\refs\\heads\\main GITHUB_REPOSITORY:ks-labs/table-reports-parser GITHUB_RUN_ID:1 GITHUB_RUN_NUMBER:1 GITHUB_SHA:0c428ff7d03f6b458fd8584b4b2b9c67f485288b GITHUB_TOKEN: GITHUB_WORKFLOW:CI GITHUB_WORKSPACE:/github/workspace HOME:/github/home]"
[CI/test] ⭐  Run actions/checkout@v2
time="2021-02-06T11:47:07-03:00" level=debug msg="Loading slug from git directory 'C:\\Users\\vinicioslc\\Documents\\GitHub\\ks-labs\\table-reports-parser\\.git'"
time="2021-02-06T11:47:07-03:00" level=debug msg="Found revision: 0c428ff7d03f6b458fd8584b4b2b9c67f485288b\n"
time="2021-02-06T11:47:07-03:00" level=debug msg="Loading revision from git directory 'C:\\Users\\vinicioslc\\Documents\\GitHub\\ks-labs\\table-reports-parser\\.git'"
time="2021-02-06T11:47:07-03:00" level=debug msg="Found revision: 0c428ff7d03f6b458fd8584b4b2b9c67f485288b\n"
time="2021-02-06T11:47:07-03:00" level=debug msg="HEAD points to '0c428ff7d03f6b458fd8584b4b2b9c67f485288b'"
time="2021-02-06T11:47:07-03:00" level=debug msg="HEAD matches \\refs\\heads\\main"
time="2021-02-06T11:47:07-03:00" level=debug msg="using github ref: \\refs\\heads\\main"
[CI/test] Skipping actions/checkout
[CI/test]   ✅  Success - actions/checkout@v2
time="2021-02-06T11:47:07-03:00" level=debug msg="Loading slug from git directory 'C:\\Users\\vinicioslc\\Documents\\GitHub\\ks-labs\\table-reports-parser\\.git'"
time="2021-02-06T11:47:07-03:00" level=debug msg="Found revision: 0c428ff7d03f6b458fd8584b4b2b9c67f485288b\n"
time="2021-02-06T11:47:07-03:00" level=debug msg="Loading revision from git directory 'C:\\Users\\vinicioslc\\Documents\\GitHub\\ks-labs\\table-reports-parser\\.git'"
time="2021-02-06T11:47:07-03:00" level=debug msg="Found revision: 0c428ff7d03f6b458fd8584b4b2b9c67f485288b\n"
time="2021-02-06T11:47:07-03:00" level=debug msg="HEAD points to '0c428ff7d03f6b458fd8584b4b2b9c67f485288b'"
time="2021-02-06T11:47:07-03:00" level=debug msg="HEAD matches \\refs\\heads\\main"
time="2021-02-06T11:47:07-03:00" level=debug msg="using github ref: \\refs\\heads\\main"
time="2021-02-06T11:47:07-03:00" level=debug msg="setupEnv => map[GITHUB_ACTION:1 GITHUB_ACTIONS:true GITHUB_ACTOR:nektos/act GITHUB_EVENT_NAME:push GITHUB_EVENT_PATH:/github/workflow/event.json GITHUB_REF:\\refs\\heads\\main GITHUB_REPOSITORY:ks-labs/table-reports-parser GITHUB_RUN_ID:1 GITHUB_RUN_NUMBER:1 GITHUB_SHA:0c428ff7d03f6b458fd8584b4b2b9c67f485288b GITHUB_TOKEN: GITHUB_WORKFLOW:CI GITHUB_WORKSPACE:/github/workspace HOME:/github/home]"
time="2021-02-06T11:47:07-03:00" level=debug msg="Loading slug from git directory 'C:\\Users\\vinicioslc\\Documents\\GitHub\\ks-labs\\table-reports-parser\\.git'"
time="2021-02-06T11:47:07-03:00" level=debug msg="Found revision: 0c428ff7d03f6b458fd8584b4b2b9c67f485288b\n"
time="2021-02-06T11:47:07-03:00" level=debug msg="Loading revision from git directory 'C:\\Users\\vinicioslc\\Documents\\GitHub\\ks-labs\\table-reports-parser\\.git'"
time="2021-02-06T11:47:07-03:00" level=debug msg="Found revision: 0c428ff7d03f6b458fd8584b4b2b9c67f485288b\n"
time="2021-02-06T11:47:07-03:00" level=debug msg="HEAD points to '0c428ff7d03f6b458fd8584b4b2b9c67f485288b'"
time="2021-02-06T11:47:07-03:00" level=debug msg="HEAD matches \\refs\\heads\\main"
time="2021-02-06T11:47:07-03:00" level=debug msg="using github ref: \\refs\\heads\\main"
time="2021-02-06T11:47:07-03:00" level=debug msg="context env => map[]"
time="2021-02-06T11:47:07-03:00" level=debug msg="context env => map[GITHUB_ACTION:1 GITHUB_ACTIONS:true GITHUB_ACTOR:nektos/act GITHUB_EVENT_NAME:push GITHUB_EVENT_PATH:/github/workflow/event.json GITHUB_REF:\\refs\\heads\\main GITHUB_REPOSITORY:ks-labs/table-reports-parser GITHUB_RUN_ID:1 GITHUB_RUN_NUMBER:1 GITHUB_SHA:0c428ff7d03f6b458fd8584b4b2b9c67f485288b GITHUB_TOKEN: GITHUB_WORKFLOW:CI GITHUB_WORKSPACE:/github/workspace HOME:/github/home]"
[CI/test] ⭐  Run actions/setup-node@v1
[CI/test]   ☁  git clone 'https://github.com/actions/setup-node' # ref=v1
[CI/test]   cloning https://github.com/actions/setup-node to C:\Users\vinicioslc\.cache\act/actions-setup-node@v1
[CI/test] Unable to pull refs/heads/v1: non-fast-forward update
[CI/test] Cloned https://github.com/actions/setup-node to C:\Users\vinicioslc\.cache\act/actions-setup-node@v1
[CI/test] Checked out v1
time="2021-02-06T11:47:08-03:00" level=debug msg="Read action &{Setup Node.js environment GitHub Setup a Node.js environment and add it to the PATH, additionally providing proxy support map[always-auth:{Set always-auth in npmrc false false} node-version:{Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0 false 10.x} registry-url:{Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN false } scope:{Optional scope for authenticating against scoped registries false } version:{Deprecated. Use node-version instead. Will not be supported after October 1, 2019 false }] map[] {node12 map[] dist/index.js  [] []} { }} from 'C:\\Users\\vinicioslc\\.cache\\act\\actions-setup-node@v1\\action.yml'"
time="2021-02-06T11:47:08-03:00" level=debug msg="About to run action &{Setup Node.js environment GitHub Setup a Node.js environment and add it to the PATH, additionally providing proxy support map[always-auth:{Set always-auth in npmrc false false} node-version:{Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0 false 10.x} registry-url:{Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN false } scope:{Optional scope for authenticating against scoped registries false } version:{Deprecated. Use node-version instead. Will not be supported after October 1, 2019 false }] map[] {node12 map[] dist/index.js  [] []} { }}"
time="2021-02-06T11:47:08-03:00" level=debug msg="type=3 actionDir=C:\\Users\\vinicioslc\\.cache\\act/actions-setup-node@v1 Workdir=C:\\Users\\vinicioslc\\Documents\\GitHub\\ks-labs\\table-reports-parser ActionCacheDir=C:\\Users\\vinicioslc\\.cache\\act actionName=/actions-setup-node@v1 containerActionDir=/actions"
[CI/test]   �  docker cp src=C:\Users\vinicioslc\.cache\act/actions-setup-node@v1 dst=/actions\
[CI/test] Exec command '[mkdir -p /actions\]'
time="2021-02-06T11:47:08-03:00" level=debug msg="Writing tarball C:\\Users\\VINICI~1\\AppData\\Local\\Temp\\act856657226 from C:\\Users\\vinicioslc\\.cache\\act/actions-setup-node@v1"
time="2021-02-06T11:47:08-03:00" level=debug msg="Stripping prefix:C:\\Users\\vinicioslc\\.cache\\act\\ src:C:\\Users\\vinicioslc\\.cache\\act/actions-setup-node@v1"
[CI/test] Extracting content from 'C:\Users\VINICI~1\AppData\Local\Temp\act856657226' to '/actions\'
[CI/test] Exec command '[node \actions\actions-setup-node@v1\dist\index.js]'
| internal/modules/cjs/loader.js:628
|     throw err;
|     ^
|
| Error: Cannot find module '/github/workspace/\actions\actions-setup-node@v1\dist\index.js'
|     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
|     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
|     at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
|     at internal/main/run_main_module.js:17:11 {
|   code: 'MODULE_NOT_FOUND',
|   requireStack: []
| }
[CI/test]   ❌  Failure - actions/setup-node@v1
time="2021-02-06T11:47:10-03:00" level=debug msg="exit with `FAILURE`: 1"
time="2021-02-06T11:47:10-03:00" level=debug msg="exit with `FAILURE`: 1"
time="2021-02-06T11:47:10-03:00" level=debug msg="exit with `FAILURE`: 1"
Error: exit with `FAILURE`: 1
```
</details>

**Comment by catthehacker** [comment]
What is the version of `act` you are running? Issue has been fixed in https://github.com/nektos/act/pull/461

**Comment by vinicioslc** [comment]
@catthehacker Thanks !

I was using the version 0.2.9 from chocolatey, now i added to PATH a version 0.2.19 from releases page, this error does not longer occurs.
but generates another error 
`npm install \r\n Maximum call stack size exceeded` , i guess its my package.json deps, i think this issue could be closed now.

**Comment by catthehacker** [comment]
Choco releases have been fixed in https://github.com/nektos/act/pull/515 so hopefully next `act` release should arrive on chocolatey.

**Comment by vinicioslc** [comment]
This will be nice !
im waiting for this.

**Comment by cplee** [comment]
@vinicioslc - just released `v0.2.20` https://chocolatey.org/packages/act-cli/0.2.20

**Comment by vinicioslc** [comment]
@cplee 
Ok, I will test it

**Comment by vinicioslc** [comment]
@cplee 
Everthing works fine ! thanks again this is an awesome tool!
