### ISSUE TITLE
Issue: zero value panic in matrix workflow

### ISSUE THREAD

**Issue by marscher** [nektos/act#885]
## System information

- Operating System: Arch Linux
- Architecture: amd64
- Docker version: 20.10.10, build b485636f4b
- Docker image used in `act`:
- `act` version: 0.2.24

## Expected behaviour
Be able to run a single workflow.

## Actual behaviour

When executing act on this repo's ()workflows, I receive the following stack trace, right after image selection (large). On another less complicated matrix the act installation works like a charm, so I suspect it has something to do with the contained workflow matrix.

## Workflow and/or repository
https://github.com/BAMWelDX/weldx/commit/23ad669b938864ef1b6a806b26964843cccc28da 

## `act` output

<details>
  <summary>Log</summary>

```none
DEBU[0000] Loading slug from git directory '/home/marscher/sources/weldx/.git' 
DEBU[0000] Found revision: 23ad669b938864ef1b6a806b26964843cccc28da 
DEBU[0000] Loading revision from git directory '/home/marscher/sources/weldx/.git' 
DEBU[0000] Found revision: 23ad669b938864ef1b6a806b26964843cccc28da 
DEBU[0000] HEAD points to '23ad669b938864ef1b6a806b26964843cccc28da' 
DEBU[0000] using github ref: refs/heads/master          
DEBU[0000] context env => map[ACT:true]                 
DEBU[0000] context needs => map[]                       
panic: reflect: call of reflect.Value.Type on zero Value

goroutine 1 [running]:
reflect.Value.Type({0x0, 0x0, 0x101000000000000})
        reflect/value.go:2249 +0x12e
github.com/nektos/act/pkg/model.(*Job).Matrix(0xc0005d5988)
        github.com/nektos/act/pkg/model/workflow.go:178 +0xd6
github.com/nektos/act/pkg/model.(*Job).GetMatrixes(0xc0001f4c00)
        github.com/nektos/act/pkg/model/workflow.go:200 +0x67
github.com/nektos/act/pkg/runner.(*runnerImpl).NewPlanExecutor(0xc00000f710, 0xc00000ec30)
        github.com/nektos/act/pkg/runner/runner.go:119 +0x2b9
github.com/nektos/act/cmd.newRunCommand.func1(0xc000496000, {0xc0004d6000, 0x0, 0x10})
        github.com/nektos/act/cmd/root.go:290 +0xa79
github.com/spf13/cobra.(*Command).execute(0xc000496000, {0xc000498300, 0x9, 0x10})
        github.com/spf13/cobra@v1.1.1/command.go:850 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000496000)
        github.com/spf13/cobra@v1.1.1/command.go:958 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.1/command.go:895
github.com/nektos/act/cmd.Execute({0x561d59046880, 0xc0003e0600}, {0x561d58eab808, 0x6})
        github.com/nektos/act/cmd/root.go:71 +0xae6
main.main()
        github.com/nektos/act/main.go:33 +0x171
```

</details>

**Comment by catthehacker** [comment]
Issue is fixed in master branch
![image](https://user-images.githubusercontent.com/31106839/141971195-c25b3ba5-185c-415d-ac62-88a0291d2a47.png)

**Comment by marscher** [comment]
Thanks, I should have tested the master version. Sry for wasting your time.

**Comment by catthehacker** [comment]
Ok, finally found the issue
Duplicate of https://github.com/nektos/act/issues/760

**Comment by marscher** [comment]
eventually it is worth releasing this fix?

**Comment by catthehacker** [comment]
@marscher yes but that is up to project owner, I can't do it myself
